Sitegeist:
  Silhouettes:
    properties:
      text:
        plain:
          type: string
          defaultValue: ''
          ui:
            inlineEditable: true
            inline:
              editorOptions:
                placeholder: '(( text plain ))'
                autoparagraph: false
                'format': {'removeFormat': true}
                'table': {}
                'list': {}
                'link': {}

        block:
          type: string
          defaultValue: ''
          ui:
            inlineEditable: true
            inline:
              editorOptions:
                placeholder: '(( text block ))'
                autoparagraph: false
                'format':
                  'strong': TRUE
                  'em': TRUE
                  'u': false
                  'sub': false
                  'sup': false
                  'del': false
                  'p': false
                  'h1': false
                  'h2': false
                  'h3': false
                  'pre': false
                  'removeFormat': true
                'table': {}
                'list': {}
                'link':
                  'a': TRUE

        free:
          type: string
          defaultValue: ''
          ui:
            inlineEditable: true
            inline:
              editorOptions:
                placeholder: '(( text ))'
                autoparagraph: true
                'format':
                  'strong': true
                  'em': true
                  'u': false
                  'sub': false
                  'sup': false
                  'del': false
                  'p': true
                  'h1': true
                  'h2': true
                  'h3': true
                  'pre': true
                  'removeFormat': true
                'table':
                  'table': true
                'list':
                  'ol': true
                  'ul': true
                'link':
                  'a': true
